version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4
jobs:
  docs-build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: javadoc
          command: |
            mkdir -p docs/apidocs
            mvn javadoc:javadoc -D maven.javadoc.skip=false -D javadocDirectory=docs/apidocs
  build-and-test:
    docker:
      - image: circleci/openjdk:10-jdk
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: run the test
          command: mvn test jacoco:report
      - run:
          name: CheckStyle
          command: mvn -DskipTests checkstyle:checkstyle
      - run:
          name: Upload coverage data to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
      - run:
          name: Code Coverage
          command: curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov
  docs-deploy:
    docker:
      - image: circleci/openjdk:10-jdk
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f0:48:d3:f9:e0:25:4f:16:df:7d:39:b9:a4:ac:0c:ae"
      - run:
          name: deploy docs
          command: |
            git config --global user.name "anthony-vitrant"
            git config --global user.email "anthony.vitrant@alumni.univ-avignon.fr"
            git clone --branch=gh-pages --depth=1 git@github.com:anthony-vitrant/ceri-m1-techniques-de-test.git gh-pages
            rm -rf gh-pages/*
            cp -R docs/apidocs/* gh-pages/
            cd gh-pages
            git add .
            git commit -m "docs: update javadoc"
            git push origin gh-pages

workflows:
  version: 2.1
  sample:
    jobs:
      - build-and-test
      - docs-build:
          requires:
            - build-and-test
      - docs-deploy:
          requires:
            - build-and-test
            - docs-build