version: 2
orbs:
  codecov: codecov/codecov@3.2.4
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: run the test
          command: mvn test
      - run:
          name: Code Coverage
          command: curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov
    branches:
      only:
        - master