version: 2
orbs:
  codecov: codecov/codecov@3.2.4
jobs:
  build:
    docker:
      - image: circleci/openjdk:10-jdk
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: run the test
          command: mvn test jacoco:report
      - run:
          name: CheckStyle
          command: mvn -DskipTests checkstyle:checkstyle
      - run:
          name: Upload coverage data to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
      - run:
          name: Code Coverage
          command: curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov
    branches:
      only:
        - master